version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    working_dir: /app/backend
    command: nodemon index.js
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: npm run dev
